# Use Ctrl-x instead of Ctrl-b
set -g prefix C-x
unbind C-b
bind C-x send-prefix

# Toggle between the last two windows using Ctrl-x Ctrl-x
bind C-x last-window

# Show list of windows using Ctrl-x "
bind '"' choose-tree -w

# Rename window using Ctrl-x A
bind A command-prompt "rename-window '%%'"

# Use Esc to enter copy mode, and Esc to exit AND jump back to the bottom
bind Escape copy-mode
bind -T copy-mode Escape send-keys -X cancel \; send-keys Down

set-option -g update-environment "SSH_AUTH_SOCK"
